title: "ROMOBROLE"
description: > # this means to ignore newlines until "baseurl:"
  Tournoi inter jeux de Romorantin
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.interjeuxromo.fr" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
email: interjeuxromo@gmail.com

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name:
  link: ""

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages','_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: 
    url: 
  - title: 
    url: 

# Build settings
markdown: kramdown
permalink: pretty
